# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iO6E8rAu5Biz_1nqiyIATb4ciuSjQ3XQ
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# 
# # --- Configuración general ---
# st.set_page_config(page_title="Chicago Cubs 2025 Dashboard", layout="wide")
# 
# # --- Cargar datos ---
# df_cubs = pd.read_csv("cubs_stats.csv")
# 
# # --- Sidebar: elegir color del background ---
# bg_color = st.sidebar.color_picker("Selecciona el color de fondo", "#0e3386")
# 
# # --- Sidebar: elegir color de los títulos ---
# title_color = st.sidebar.color_picker("Selecciona el color de los títulos", "#FFFFFF")
# 
# # --- Cargar CSS base ---
# with open("styles.css") as f:
#     css = f.read()
# 
# # --- CSS global + KPIs Glassmorphism + Inter font ---
# st.markdown(
#     f"""
#     <style>
# 
#     /* ====== Fuente Inter ====== */
#     @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&display=swap');
# 
#     html, body, [class*="css"] {{
#         font-family: 'Inter', sans-serif !important;
#     }}
# 
#     {css}
# 
#     /* ====== Fondo del dashboard ====== */
#     [data-testid="stAppViewContainer"],
#     .stApp,
#     .main,
#     .block-container {{
#         background-color: {bg_color} !important;
#     }}
# 
#     /* ====== Sidebar siempre en negro ====== */
#     [data-testid="stSidebar"] * {{
#         color: black !important;
#     }}
# 
#     /* ====== Sidebar con emojis ====== */
#     [data-testid="stSidebar"] .sidebar-item {{
#         font-size: 16px !important;
#     }}
# 
#     /* ====== Titulares del dashboard ====== */
#     h1, h2, h3, h4, h5, h6,
#     .stTabs [data-baseweb="tab"] {{
#         color: {title_color} !important;
#     }}
# 
#     /* ====== Tab activa ====== */
#     .stTabs [data-baseweb="tab"][aria-selected="true"] {{
#         color: {title_color} !important;
#         font-weight: bold !important;
#     }}
# 
#     /* ====== KPIs estilo glassmorphism ====== */
#     .glass-kpi {{
#         background: rgba(255, 255, 255, 0.15);
#         border-radius: 18px;
#         padding: 18px;
#         text-align: center;
#         backdrop-filter: blur(10px);
#         -webkit-backdrop-filter: blur(10px);
#         border: 1px solid rgba(255,255,255,0.3);
#         box-shadow: 0 4px 15px rgba(0,0,0,0.15);
#         margin-bottom: 12px;
#     }}
# 
#     .glass-title {{
#         font-size: 16px;
#         font-weight: 600;
#         margin-bottom: 6px;
#         color: {title_color} !important;
#     }}
# 
#     .glass-value {{
#         font-size: 28px;
#         font-weight: 700;
#         color: {title_color} !important;
#     }}
# 
#     </style>
#     """,
#     unsafe_allow_html=True
# )
# 
# # Validar columnas clave
# required_cols = [
#     "last_name, first_name", "hit", "home_run", "walk", "batting_avg",
#     "on_base_percent", "slg_percent", "player_age", "pa"
# ]
# missing = [c for c in required_cols if c not in df_cubs.columns]
# if missing:
#     st.error(f"Faltan columnas en el CSV: {missing}. Revisa los nombres exactos.")
#     st.stop()
# 
# # --- SIDEBAR: filtros ---
# st.sidebar.title("🧰 Filtros")
# 
# metric = st.sidebar.selectbox(
#     "📌 Selecciona una métrica:",
#     ["batting_avg", "hit", "home_run", "on_base_percent", "slg_percent"],
#     index=0,
#     key="sidebar_metric"
# )
# 
# top_n = st.sidebar.slider(
#     "📊 Selecciona cuántos jugadores mostrar:",
#     min_value=3,
#     max_value=len(df_cubs),
#     value=5,
#     key="sidebar_top_n"
# )
# 
# # Filtro por año si existe
# if "year" in df_cubs.columns:
#     years = sorted(df_cubs["year"].unique())
#     selected_year = st.sidebar.selectbox("📅 Selecciona un año:", years, index=len(years)-1)
#     df_filtered = df_cubs[df_cubs["year"] == selected_year].copy()
# else:
#     df_filtered = df_cubs.copy()
# 
# # Ordenar por métrica global
# df_sorted_by_metric = df_filtered.sort_values(by=metric, ascending=False)
# 
# # --- HEADER PRINCIPAL ---
# st.markdown(
#     f"""
#     <div style="display:flex; align-items:center; gap:15px; justify-content:center;">
#         <h1 style="color:{title_color}; text-align:center; margin:0;">🐻 Chicago Cubs 2025 Batting Dashboard ⚾</h1>
#     </div>
#     """,
#     unsafe_allow_html=True
# )
# 
# st.markdown(
#     f"<h3 style='text-align:center; color:{title_color}; margin-top:-10px;'>Análisis interactivo basado en estadísticas de la temporada 2025 (Baseball Savant)</h3>",
#     unsafe_allow_html=True
# )
# 
# # --- KPIs GLOBALS (Glassmorphism Cards) ---
# st.markdown(f"### <span style='color:{title_color};'>📊 Team Summary — KPIs Globales</span>", unsafe_allow_html=True)
# 
# col1, col2, col3, col4 = st.columns(4)
# 
# with col1:
#     st.markdown(f"""
#         <div class="glass-kpi">
#             <div class="glass-title">Total Hits</div>
#             <div class="glass-value">{int(df_filtered["hit"].sum())}</div>
#         </div>
#     """, unsafe_allow_html=True)
# 
# with col2:
#     st.markdown(f"""
#         <div class="glass-kpi">
#             <div class="glass-title">Total Home Runs</div>
#             <div class="glass-value">{int(df_filtered["home_run"].sum())}</div>
#         </div>
#     """, unsafe_allow_html=True)
# 
# with col3:
#     st.markdown(f"""
#         <div class="glass-kpi">
#             <div class="glass-title">Average Batting AVG</div>
#             <div class="glass-value">{round(df_filtered["batting_avg"].mean(), 3)}</div>
#         </div>
#     """, unsafe_allow_html=True)
# 
# with col4:
#     st.markdown(f"""
#         <div class="glass-kpi">
#             <div class="glass-title">Team OBP (On-Base %)</div>
#             <div class="glass-value">{round(df_filtered["on_base_percent"].mean(), 3)}</div>
#         </div>
#     """, unsafe_allow_html=True)
# 
# st.markdown("<hr>", unsafe_allow_html=True)
# 
# # --- TABS ---
# tab1, tab2, tab3 = st.tabs(["🏅 Top Batters", "📈 Performance Evolution", "⚾ Team Production Breakdown"])
# 
# 
# # ---------------- TAB 1 ----------------
# with tab1:
#     st.header("🏅 Top Batters")
# 
#     top_players = df_sorted_by_metric.head(top_n)
# 
#     base_blue = ["#0e3386", "#2e5aa7", "#4c7fc9", "#6ea3e0", "#8bbef2"]
#     blue_palette = base_blue[:top_n] if top_n <= len(base_blue) else (base_blue * ((top_n // len(base_blue)) + 1))[:top_n]
# 
#     fig, ax = plt.subplots(figsize=(8, max(3, top_n * 0.6)))
#     sns.barplot(data=top_players, x=metric, y="last_name, first_name", palette=blue_palette, ax=ax)
# 
#     # ❌ Ya NO se colorean los textos del gráfico
#     ax.set_title(f"Top {top_n} jugadores por {metric}", fontsize=13, weight='bold')
#     ax.set_xlabel(metric.replace("_", " ").title())
#     ax.set_ylabel("Jugador")
# 
#     sns.despine()
#     plt.tight_layout()
#     st.pyplot(fig)
# 
# 
# # ---------------- TAB 2 ----------------
# with tab2:
#     st.header("📈 Performance Evolution")
# 
#     fig, ax = plt.subplots(figsize=(8,5))
#     sns.scatterplot(
#         data=df_filtered,
#         x="player_age",
#         y=metric,
#         hue="last_name, first_name",
#         s=80,
#         ax=ax
#     )
# 
#     # ❌ No color dinámico
#     ax.set_title(f"{metric.replace('_',' ').title()} vs Player Age", fontsize=13, weight='bold')
#     ax.set_xlabel("Edad del jugador")
#     ax.set_ylabel(metric.replace("_", " ").title())
# 
#     ax.legend([], [], frameon=False)
#     sns.despine()
#     plt.tight_layout()
#     st.pyplot(fig)
# 
# 
# # ---------------- TAB 3 ----------------
# with tab3:
#     st.header("⚾ Team Production Breakdown")
# 
#     metrics = ["hit", "home_run", "walk"]
#     top_for_breakdown = df_sorted_by_metric.head(top_n)[["last_name, first_name"] + metrics].set_index("last_name, first_name")
#     top_for_breakdown["total"] = top_for_breakdown.sum(axis=1)
#     top_for_breakdown = top_for_breakdown.sort_values("total", ascending=False).drop(columns="total")
# 
#     cubs_palette = {"hit": "#0e3386", "home_run": "#cc3433", "walk": "#5a8fd8"}
# 
#     fig, ax = plt.subplots(figsize=(9, max(4, top_n * 0.6)))
#     top_for_breakdown.plot(kind="bar", stacked=True, ax=ax, color=[cubs_palette[m] for m in metrics])
# 
#     # ❌ No color dinámico
#     ax.set_title(f"Producción Ofensiva — Top {top_n} Jugadores", fontsize=14, weight='bold')
#     ax.set_xlabel("Jugador")
#     ax.set_ylabel("Totales (Hits, HR, Walks)")
# 
#     plt.xticks(rotation=45, ha='right')
#     sns.despine()
#     plt.tight_layout()
#     st.pyplot(fig)